### ISSUE TITLE
Broken Build: missing @dimen/Bold, R.id.bicycleText, and R.id.transitText

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#11]
I pulled the latest snapshot from this repo and the project says it's missing @dimen/Bold, R.id.bicycleText, and R.id.transitText so it cannot build. Are there some new files in res/ missing?

**Comment by alaurenz** [comment]
I am having the same issue.

**Comment by dutchscout** [comment]
Just added the file with 'bold' (new file dimens.xml) - sorry about that :/

The other values (bicycleText and transitText) should already be in the current version of the repository (https://github.com/alaurenz/metrobike/blob/master/HelloMetroBike/res/values/strings.xml).

For them, I suggest doing a 'clean' on the project, since Eclipse may not recognize the new strings until the new values are added to the generated R.java file (Project-> Clean...-> Clean all projects).

Let me know if this (pull + clean all) fixes the issue for you.

**Comment by CoolCapri** [comment]
Build succeeded! Thanks.
