### ISSUE TITLE
Add smarter zooming to NavigateActivity

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#138]
Add smarter zooming to NavigateActivity so that it zooms in for every step (or leg?).

**Comment by dutchscout** [comment]
I need to check if each step has getNEBound/getSWBound

Jaylen

Sent from my iPhone

On May 21, 2013, at 19:53, Shuo Wang notifications@github.com wrote:

Add smarter zooming to NavigateActivity so that it zooms in for every step
(or leg?).

—
Reply to this email directly or view it on
GitHubhttps://github.com/alaurenz/metrobike/issues/138
.

**Comment by sw11** [comment]
It turns out it takes too much time to zoom. 
So we just show the step or leg instead of zooming it.
