### ISSUE TITLE
Seattle to New York

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#160]
@alaurenz @meganca @coreyh3 
I have a question about searching a route from seattle to new york.
The app tried to search this route and then return back to the MainActivity without any error dialog pops up?
So my question is how do we handle this case?
Thanks

**Comment by dutchscout** [comment]
Does our app break when this happens?

**Comment by sw11** [comment]
No, It just go back to the MainActivity.
(Pretending nothing happened)

**Comment by dutchscout** [comment]
Could someone with a device try this search and capture the logcat output to a text file?

**Comment by dutchscout** [comment]
I added a unit test for Seattle to New York.  The app correctly rejects the route results for being over 500km long, but the test took 10.5 minutes to run, partially because of our intense Logcat output.  I may let this run once on Jenkins to see if it's faster, but if not, we'll need to pull it because it's too long :/

**Comment by dutchscout** [comment]
Large unit test removed (last build was 46 minutes long).
