### ISSUE TITLE
Create Instructions Document

### ISSUE THREAD

**Issue by coreyh3** [alaurenz/metrobike#4]

**Comment by CoolCapri** [comment]
I have finished Parts A and C, and the ZFR instructions document is available on our Google Drive shared folder. For B and D, I would work with Sam and it would be great if you guys can help out, because I don't know details about B and D, especially D.

**Comment by CoolCapri** [comment]
Part B is now finished.

**Comment by CoolCapri** [comment]
Thanks to Sam, Part D is almost done.

**Comment by CoolCapri** [comment]
Due to the adding of Map UI, we cannot run the app on simulator. Should we remove the simulator setup step from ZFR instruction? Also please set up a good way to run the app. Do we recommend connecting a real device to the computer with a cord to run/debug? Or, do we upload APK installation package somewhere and developers downloads it and run/debug it?

**Comment by dutchscout** [comment]
Added the part about not running in a simulator.
Added instructions for adding Google Play API support.

Proofread document (basic read), looks good.
