### ISSUE TITLE
Search Activity

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#41]
Find button in search activity crash. 
The history info is too small in phone screen.
It seems that there is no button to disable the keyword after entering the address.

**Comment by dutchscout** [comment]
To disable the autocomplete feature, you may need to use a different entry widget (?), or it may be a property.

**Comment by csmengwan** [comment]
Should be fixed now

**Comment by CoolCapri** [comment]
I am working with Qinyuan. The reason why find button crashes (NullPointerException) is because it sends a list of routes to results but resultActivity does not handle the intent extra properly. Qinyuan has now pushed a new resultActivity and it will work with find. Try it!

The Layout of history info needs to be polished, but I currently have no idea how to make it better.

Disable the keyword? What do you mean by this?

**Comment by sw11** [comment]
The find button crashes with java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
When there is no input and then I click find.
Sorry typo: keyword -> keyboard
I am testing on the small screen phone which the keyboard covers the find button.

**Comment by CoolCapri** [comment]
Did you still get the java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0 problem?

**Comment by csmengwan** [comment]
No

ÔÚ 2013-05-05 03:36:00£¬"Shuo Wang" notifications@github.com Ð´µÀ£º

Did you still get the java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0 problem?

¡ª
