### ISSUE TITLE
Limited number of steps issue.

### ISSUE THREAD

**Issue by csmengwan** [alaurenz/metrobike#69]
It looks like the solution has very limited number of steps and so the drawing or the map is weird. Or does the string polyline thing gets fixed?

**Comment by dutchscout** [comment]
This is a good issue to note.  At the moment, our drawn route path is a simple line from the start to the end of each step.  Google maps passes back a polyline string which has encoded in it a lot more points that would allow us to follow paths like roads or bicycle trails, but we have to decode them ourselves.  We found some decoding code, but it's not working yet.  Also, to properly do the algorithm-based route assembly, we may need to find/write an encoding library as well, since the list of locations we get back can be so large for some queries that the intent-passing mechanism fails and the app eventually crashes.

I believe we will get the route-drawing problem fixed in beta phase.  Until then, I think we're stuck with blocky lines. :/

**Comment by alaurenz** [comment]
I fixed this issue so now the polylines are plotted correctly. Also the Step object now stores the encoded polyline and has a getPolyLinePoints method which decodes the associated polyLine into a list of Locations.
