### ISSUE TITLE
Bug! The first history option Paul G. Allen one give me routes with different start and end point

### ISSUE THREAD

**Issue by csmengwan** [alaurenz/metrobike#72]

**Comment by dutchscout** [comment]
It looks like the first route takes you to university of washington medical center, while the other route takes you to Schmitz hall, for university of washington campus.

My guess is that this is because we asked for 'University of Washington', so google maps came up with 2 different meanings for that destination.

**Comment by CoolCapri** [comment]
I have changed dest to a more specific one.
